# Generated by Django 4.1 on 2022-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_idx_entry_idx_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='summary_meta',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
