# Generated by Django 4.1 on 2022-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of the category. Max length is 255.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Slug of the category. Max length is 255.', max_length=60, unique=True, verbose_name='Slug'),
        ),
    ]
